# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  orderer.votingsys.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.votingsys.com
    container_name: orderer.votingsys.com
    networks:
      - byfn

  orderer1.votingsys.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.votingsys.com
    container_name: orderer1.votingsys.com
    networks:
      - byfn

  peer0.issuer.votingsys.com:
    container_name: peer0.issuer.votingsys.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.issuer.votingsys.com
    networks:
      - byfn

  peer0.broker.votingsys.com:
    container_name: peer0.broker.votingsys.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.broker.votingsys.com
    networks:
      - byfn

  peer1.broker.votingsys.com:
    container_name: peer1.broker.votingsys.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.broker.votingsys.com
    networks:
      - byfn

  peer0.client.votingsys.com:
    container_name: peer0.client.votingsys.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.client.votingsys.com
    networks:
      - byfn

  peer1.client.votingsys.com:
    container_name: peer1.client.votingsys.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.client.votingsys.com
    networks:
      - byfn

  peer0.hkex.votingsys.com:
    container_name: peer0.hkex.votingsys.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hkex.votingsys.com
    networks:
      - byfn

  peer1.hkex.votingsys.com:
    container_name: peer1.hkex.votingsys.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hkex.votingsys.com
    networks:
      - byfn

  peer0.sfc.votingsys.com:
    container_name: peer0.sfc.votingsys.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sfc.votingsys.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hkex.votingsys.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hkex.votingsys.com/peers/peer0.hkex.votingsys.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hkex.votingsys.com/peers/peer0.hkex.votingsys.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hkex.votingsys.com/peers/peer0.hkex.votingsys.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hkex.votingsys.com/users/Admin@hkex.votingsys.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.votingsys.com
      - orderer1.votingsys.com
      - peer0.issuer.votingsys.com
      - peer0.broker.votingsys.com
      - peer1.broker.votingsys.com
      - peer0.client.votingsys.com
      - peer1.client.votingsys.com
      - peer0.hkex.votingsys.com
      - peer1.hkex.votingsys.com
      - peer0.sfc.votingsys.com
    networks:
      - byfn

