# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.votingsys.com:
    container_name: orderer.votingsys.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/votingsys.com/orderers/orderer.votingsys.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/votingsys.com/orderers/orderer.votingsys.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  orderer1.votingsys.com:
    container_name: orderer1.votingsys.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer1/orderer1.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Orderer1MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer1/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer1/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer1/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer1/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer1/orderer1.genesis.block
    - ../crypto-config/ordererOrganizations/votingsys.com/orderers/orderer1.votingsys.com/msp:/var/hyperledger/orderer1/msp
    - ../crypto-config/ordererOrganizations/votingsys.com/orderers/orderer1.votingsys.com/tls/:/var/hyperledger/orderer1/tls
    ports:
      - 11050:7050

  peer0.issuer.votingsys.com:
    container_name: peer0.issuer.votingsys.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.issuer.votingsys.com
      - CORE_PEER_ADDRESS=peer0.issuer.votingsys.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.issuer.votingsys.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/issuer.votingsys.com/peers/peer0.issuer.votingsys.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/issuer.votingsys.com/peers/peer0.issuer.votingsys.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer0.broker.votingsys.com:
    container_name: peer0.broker.votingsys.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.broker.votingsys.com
      - CORE_PEER_ADDRESS=peer0.broker.votingsys.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.broker.votingsys.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/broker.votingsys.com/peers/peer0.broker.votingsys.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/broker.votingsys.com/peers/peer0.broker.votingsys.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053

  peer1.broker.votingsys.com:
    container_name: peer1.broker.votingsys.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.broker.votingsys.com
      - CORE_PEER_ADDRESS=peer1.broker.votingsys.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.broker.votingsys.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.broker.votingsys.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/broker.votingsys.com/peers/peer1.broker.votingsys.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/broker.votingsys.com/peers/peer1.broker.votingsys.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8151:7051
      - 8153:7053

  peer0.client.votingsys.com:
    container_name: peer0.client.votingsys.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.client.votingsys.com
      - CORE_PEER_ADDRESS=peer0.client.votingsys.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.client.votingsys.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/client.votingsys.com/peers/peer0.client.votingsys.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/client.votingsys.com/peers/peer0.client.votingsys.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer1.client.votingsys.com:
    container_name: peer1.client.votingsys.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.client.votingsys.com
      - CORE_PEER_ADDRESS=peer1.client.votingsys.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.client.votingsys.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.client.votingsys.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/client.votingsys.com/peers/peer1.client.votingsys.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/client.votingsys.com/peers/peer1.client.votingsys.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9151:7051
      - 9153:7053

  peer0.hkex.votingsys.com:
    container_name: peer0.hkex.votingsys.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hkex.votingsys.com
      - CORE_PEER_ADDRESS=peer0.hkex.votingsys.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hkex.votingsys.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hkex.votingsys.com/peers/peer0.hkex.votingsys.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hkex.votingsys.com/peers/peer0.hkex.votingsys.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053

  peer1.hkex.votingsys.com:
    container_name: peer1.hkex.votingsys.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hkex.votingsys.com
      - CORE_PEER_ADDRESS=peer1.hkex.votingsys.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hkex.votingsys.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hkex.votingsys.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hkex.votingsys.com/peers/peer1.hkex.votingsys.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hkex.votingsys.com/peers/peer1.hkex.votingsys.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10151:7051
      - 10153:7053

  peer0.sfc.votingsys.com:
    container_name: peer0.sfc.votingsys.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.sfc.votingsys.com
      - CORE_PEER_ADDRESS=peer0.sfc.votingsys.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sfc.votingsys.com:7051
      - CORE_PEER_LOCALMSPID=Org5MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sfc.votingsys.com/peers/peer0.sfc.votingsys.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sfc.votingsys.com/peers/peer0.sfc.votingsys.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053

